### ISSUE TITLE
Use SyntacticVersioning to stub release notes

### ISSUE THREAD

**Issue by TheAngryByrd** [TheAngryByrd/MiniScaffold#167]
**Is your feature request related to a problem? Please describe.**

SyntacticVersioning can look at API diffs to figure out what the next release version should.

[This blog](https://chester.codes/automating-dotnet-library-versioning-synver/) describes the process a bit.

**Describe the solution you'd like**

Have 2 tasks.

`CreateReleaseStub` that would generate the next version number and release date. This would be used before releasing
`GenerateApiDiff` that would generate the `.lson` file containing the current versions API.

**Describe alternatives you've considered**

Hand doing it

**Additional context**

**Comment by rmunn** [comment]
Also worth considering the https://keepachangelog.com/en/1.0.0/ format, which IIRC has good [FAKE integration](https://fake.build/apidocs/v5/fake-core-changelog.html).

**Comment by TheAngryByrd** [comment]
Oh nice. Changelog support would be my preference. Want to open an issue about it specifically @rmunn ?

**Comment by rmunn** [comment]
Okay, created https://github.com/TheAngryByrd/MiniScaffold/issues/172.

**Comment by baronfel** [comment]
I recently added the sort-of-opposite to this to FCS to help prevent me from accidentally breaking binary compatibility: https://github.com/fsharp/FSharp.Compiler.Service/pull/930

This code could make a good basis for a feature like this in my opinion, though: instead of asserting that some desired version is at least some minimum version bump, you could more simply run the `bump` function on the before-and-after DLLs and use the result of that as the basiis for your new changelog.

**Comment by TheAngryByrd** [comment]
While this is a neat idea, I think it's a bit too much work and is another thing the box that might too much to fit in.
