### ISSUE TITLE
Add support for alternate VCS hosts: Bitbucket etc

### ISSUE THREAD

**Issue by simonmcconnell** [TheAngryByrd/MiniScaffold#174]
I'd like to host my repo on bitbucket.

**Comment by TheAngryByrd** [comment]
@simonmcconnell You can push your git repo to bitbucket, you'll just have to remove things like GitHub Pages and GitHub Releases from the build script. Are there any comparable features bitbucket has for those?

**Comment by rmunn** [comment]
https://confluence.atlassian.com/bitbucket/publishing-a-website-on-bitbucket-cloud-221449776.html appears to be the Bitbucket equivalent of GH Pages. They also have a "Downloads" section of each repo, and https://confluence.atlassian.com/bitbucket/deploy-build-artifacts-to-bitbucket-downloads-981144761.html contains instructions for uploading the results of your build (using their Bitbucket Pipelines feature, but since it's a simple REST API it wouldn't be hard to use Bitbucket to hold build artifacts created by other build servers).

I don't use Bitbucket Pipelines myself (the free plan only provides 50 build minutes per month, not enough for anything more than basic testing) so I don't have the know-how (or interest) to submit a PR adding Bitbucket deployment targets to the build.fsx script, but those doc links should help anyone who wants to work on that.

**Comment by rmunn** [comment]
Note that once #175 is merged, there will be a few places in the build script where GitHub links are generated that compare revision A to revision B, e.g. [here](https://github.com/TheAngryByrd/MiniScaffold/blob/90897dceeb602083d2785568ad950dfbe3da0b33/Content/Library/build.fsx#L156) and [here](https://github.com/TheAngryByrd/MiniScaffold/blob/90897dceeb602083d2785568ad950dfbe3da0b33/Content/Library/build.fsx#L316). If you're using a different VCS host, you'll want to update the `sprintf` format string that creates those links to whatever is appropriate for the host you're using. The fastest way to find all URLs that need updating is probably going to be to do a text search for everywhere that `gitHubRepoUrl` is used throughout the code.

**Comment by TheAngryByrd** [comment]
Going to close since this has been answered
