### ISSUE TITLE
CHANGELOG release strategy

### ISSUE THREAD

**Issue by TheAngryByrd** [TheAngryByrd/MiniScaffold#182]
[![](https://api.gh-polls.com/poll/01DZPN1HMBK07BP2ZK9BHW7KHD/Blank%20Release)](https://api.gh-polls.com/poll/01DZPN1HMBK07BP2ZK9BHW7KHD/Blank%20Release/vote)
[![](https://api.gh-polls.com/poll/01DZPN1HMBK07BP2ZK9BHW7KHD/Duplicated)](https://api.gh-polls.com/poll/01DZPN1HMBK07BP2ZK9BHW7KHD/Duplicated/vote)

**Comment by TheAngryByrd** [comment]
Hey all 👋 

We have a inflection point over in #175.  We're switching to using a [CHANGELOG](https://keepachangelog.com/en/1.0.0/) instead of the `RELEASE_NOTES` we've previously used.  

One of the interesting points here is how we handle the section for pre-releases and releases.  According to https://github.com/olivierlacan/keep-a-changelog/issues/146, each prerelease should have its own section that stays around.  In the previous `RELEASE_NOTES` model, we only updated the pre-release section until it was a releasable item.  So the question is, what do we put in the final release section?  Do we duplicate the current pre-release notes as a summary or do we leave it blank and let people scroll through the various changes over time?

@baronfel @andrewpucci @ominestre @jdodds @rmunn

**Comment by baronfel** [comment]
I lean towards duplicating them for the release given how this flows into other consumption sources, specifically nuget/fuget.  The release notes there are what's shown to users (imagine the VS nuget UI here), and seeing nothing there would be very confusing for them.

As an alternative, the release in the changelog.md could be empty, but the ReleaseNotes written into the nuget package could be the result of concatenating the other prerelease entries.

**Comment by TheAngryByrd** [comment]
> I lean towards duplicating them for the release given how this flows into other consumption sources, specifically nuget/fuget. The release notes there are what's shown to users (imagine the VS nuget UI here), and seeing nothing there would be very confusing for them.
> 
> As an alternative, the release in the changelog.md could be empty, but the ReleaseNotes written into the nuget package could be the result of concatenating the other prerelease entries.

Sorry I didn't explain that enough.  The github/nuget release notes would be aggregated together, this is specifically for the CHANGELOG file's release section itself.

**Comment by rmunn** [comment]
To clarify with an example, say the changelog looks like this before release:

```markdown
## [Unreleased]
Official release at last!
## [1.0.0-rc.1] - date
### Fixed
- A few bugs fixed in RC
## [1.0.0-beta.2] - date
### Fixed
- A few more bugs
## [1.0.0-beta.1] - date
### Fixed
- A few bugs fixed in beta
## [1.0.0-alpha.1] - date
### Added
- Many new features in 1.0.0
### Fixed
- A few bugs fixed in alpha
```

Either way, whether we go with the "Blank Release" option or the "Duplicated" option, the NuGet and GitHub release notes will be aggregated together and look like this:

```markdown
## [1.0.0] - date
Official release at last!
### Added
- Many new features in 1.0.0
### Fixed
- A few bugs fixed in RC
- A few more bugs
- A few bugs fixed in beta
- A few bugs fixed in alpha
```

The question is what to put in the [1.0.0] section of the CHANGELOG.md file. Should it just contain "Official release at last!" (the "Blank Release" option), or should it duplicate the aggregate bug list (the "Duplicated" option)?

**Blank Release** option means the CHANGELOG.md would end up looking like:

```markdown
## [1.0.0] - date
Official release at last!
## [1.0.0-rc.1] - date
### Fixed
- A few bugs fixed in RC
## [1.0.0-beta.2] - date
### Fixed
- A few more bugs
## [1.0.0-beta.1] - date
### Fixed
- A few bugs fixed in beta
## [1.0.0-alpha.1] - date
### Added
- Many new features in 1.0.0
### Fixed
- A few bugs fixed in alpha
```

This is what @baronfel was suggesting in [his second paragraph](https://github.com/TheAngryByrd/MiniScaffold/issues/182#issuecomment-579382484).

Advantage: no duplication of info in the changelog itself. Disadvantages: the entry for 1.0.0 in the changelog now does not match what was put in GitHub and/or NuGet, and the NuGet/GitHub release notes cannot be found verbatim anywhere in the Git commit log; if you wanted to recreate them for any reason, you'd have to manually reconstruct them by pasting different parts of the changelog together.

**Duplicated** option means the CHANGELOG.md would end up looking like this:


```markdown
## [1.0.0] - date
Official release at last!
### Added
- Many new features in 1.0.0
### Fixed
- A few bugs fixed in RC
- A few more bugs
- A few bugs fixed in beta
- A few bugs fixed in alpha
## [1.0.0-rc.1] - date
### Fixed
- A few bugs fixed in RC
## [1.0.0-beta.2] - date
### Fixed
- A few more bugs
## [1.0.0-beta.1] - date
### Fixed
- A few bugs fixed in beta
## [1.0.0-alpha.1] - date
### Added
- Many new features in 1.0.0
### Fixed
- A few bugs fixed in alpha
```

Advantages: changelog entry for 1.0.0 matches what was submitted to NuGet and GitHub, and if it needs to be recreated for any reason, it's right there in the file (and preserved in the Git commit history). Disadvantage: all the fixes, additions, etc. from the 1.0.0 prereleases are duplicated in the final changelog entry.

I'm leaning towards the "Duplicated" option because I think having the NuGet/GitHub release info stored somewhere in the Git commit log (and easy to re-create later if you need it) is more important than having some duplicated text in the CHANGELOG.md itself. But it's worth noting that in https://github.com/olivierlacan/keep-a-changelog/issues/146, nobody seems to have suggested a duplicated 1.0.0 entry; the discussion there all went with what we are calling the "Blank Release" option. (Of course, that's probably because if you're updating your changelog by hand, the "Blank Release" option is far, far easier.)

**Comment by rmunn** [comment]
@TheAngryByrd Whoops. I accidentally voted twice, once for each option. It seems the `polls` bot does *not* keep track of who voted for what, so when I clicked on the "Blank Release" option after voting for "Duplicated", it logged both those votes as valid. You should subtract one "Blank Release" vote from the final total to get the actual total: I intended to vote for "Duplicated", and my vote for "Blank Release" was not intentional.

**Comment by TheAngryByrd** [comment]
Going with duplicating.
