### ISSUE TITLE
How can I use miniscaffold for an existing project

### ISSUE THREAD

**Issue by halcwb** [TheAngryByrd/MiniScaffold#189]
**Is your feature request related to a problem? Please describe.**
I have a number of libraries that currently are depending on the 'old project scaffold'. 

**Describe the solution you'd like**
I want to switch to your `MiniScaffold` (not so mini anymore, I think ;-)). Is there an easy/recommended way to do this.

**Describe alternatives you've considered**
I consider creating a fresh instance and then copy paste everything (the code files) over.

**Additional context**
NA

**Comment by TheAngryByrd** [comment]
> I consider creating a fresh instance and then copy paste everything (the code files) over.

Yeah this will be the best case for now.  I don't know if I can make too many assumptions about your project to make a script that would help without it being a bunch of pain as well 😿.

This checklist should be helpful though:

- [ ] Copy over all projects in your `src/`, `tests`, and `sln` file.
- [ ] Note any modifications to your own `build.fsx` and compare them to the one generated
  - [ ] Miniscaffold's build.fsx assumes the new sdk project format for your projects, so if you need to do that [this is a decent guide](https://natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/)
  - [ ] Also note any differences in the scaffolded projects, we fill out [title and description](https://github.com/TheAngryByrd/MiniScaffold/blob/master/Content/Library/src/MyLib.1/MyLib.1.fsproj#L8-L9) to populate your nuget packages.
  - [ ] Also assumes being able to use `dotnet test` so you'll have to see if your current test framework has an adapter
  - [ ] We recently changed over to using [CHANGELOG](https://keepachangelog.com/en/1.0.0/) for release notes. I do have a [helper script](https://github.com/TheAngryByrd/MiniScaffold/blob/master/tools/releaseToChangelog.fsx) that can move make the transition easier from the `RELEASE_NOTES` format. It's not perfect because it assumes a lot about your format but it's a head start.
- [ ] Note any changes to your `paket.depedencies` and add them
- [ ] Documentation generation is completely different from ProjectScaffold's, this would be the biggest shift
- [ ] Note any major differences between your current CI pipelines and the ones provided currently.

**Comment by halcwb** [comment]
Great thanks. I am going to give this a shot!
