### ISSUE TITLE
[Question] How to turn parallel test execution off?

### ISSUE THREAD

**Issue by gsvgit** [TheAngryByrd/MiniScaffold#221]
I use Expexto for testing and for manual tests execution I specify 
```
open Expecto

[<EntryPoint>]
let main argv =
    let config = { defaultConfig with parallel = false }
    Tests.runTestsInAssembly config argv

```
Looks like this code is ignored while executing tests from the build script. How can I turn parallel tests execution off in this case?

**Comment by TheAngryByrd** [comment]
Short Answer: We use to run tests in `dotnet test`.  [Here's how you'd configure it.](https://github.com/YoloDev/YoloDev.Expecto.TestSdk#configuration)

Long Answer: 
Yeah this will be a bit confusing since we're using `dotnet test` (using [YoloDev.Expecto.TestSdk](https://github.com/YoloDev/YoloDev.Expecto.TestSdk#configuration)) and not `dotnet run` to run the tests via the build script.  Reason why we're using `dotnet test` is other things like [AltCover](https://github.com/SteveGilham/altcover) integrate seamlessly without having to know about Expecto.  Reason why it doesn't pick up your config changes is because `YoloDev.Expecto.TestSdk` has to [scan the assembly[(https://github.com/YoloDev/YoloDev.Expecto.TestSdk/blob/master/src/YoloDev.Expecto.TestSdk/discovery.fs#L58-L79) for tests and isn't running the program via `main`. [I brought up configuring Expecto thru YoloDev in this PR](https://github.com/YoloDev/YoloDev.Expecto.TestSdk/pull/21)  and even tho it is closed, some variant of it made it into the main repo.

**Comment by gsvgit** [comment]
Thank you!
