### ISSUE TITLE
Pull request template mention Appium instead of ProjectName 

### ISSUE THREAD

**Issue by wallymathieu** [TheAngryByrd/MiniScaffold#64]
## Description

The scaffolded pull request template mention: `Appium`. This should perhaps be replaced by something else.

## Expected Behavior

As a user of MiniScaffold I would assume that it would use the entered project name when I do

```
dotnet new mini-scaffold -n MyCoolNewLib --githubUsername MyGithubUsername
```

i.e. `MyCoolNewLib`

## Known workarounds

A known workaround is simply to change it after scaffolding.

**Comment by TheAngryByrd** [comment]
Let me make sure I've following.  

You entered `dotnet new mini-scaffold -n MyCoolNewLib --githubUsername MyGithubUsername` but you got a folder with `MyCoolNewLib` instead of `Appium`.  

If you want to specify a name you can replace `MyCoolNewLib` with `Appium`. https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new?tabs=netcore2x#options

Or am I misunderstanding something?

**Comment by wallymathieu** [comment]
You would not expect to get `Appium` when you have specified `MyCoolNewLib` as the project name:

https://github.com/TheAngryByrd/MiniScaffold/blame/master/.github/PULL_REQUEST_TEMPLATE.md#L7

**Comment by TheAngryByrd** [comment]
Ahh good call!

**Comment by wallymathieu** [comment]
Thanks!
